### ISSUE TITLE
WP-CFM silently fails to pull config on Pantheon with Quicksilver hooks

### ISSUE THREAD

**Issue by elvismdev** [forumone/wp-cfm#119]
After code is deployed to Pantheon platform via git, it seems WP-CFM fails to apply the latest config when running the `wp config pull all` command. Good to check if there is something producing it from the plugin side of things.

**Comment by gbeezus** [comment]
I think the issue is here: https://github.com/forumone/wp-cfm/blob/master/wp-cfm.php#L64

Because the context of wp cli is slightly different "code/web/wp" vs "code/web" the setting for the config_dir is off.
I think that that line should read:
`$config_dir = untrailingslashit($_ENV['DOCROOT']) . '/private/config';`
or 
`$config_dir = $_ENV['DOCROOT'] . 'private/config';`

**Comment by timnolte** [comment]
@elvismdev I think we should get the PR from @gbeezus merged into the next release. This patch has been applied and tested on the Forum One website. I'm going to apply it also to Vilcek and confirm.

**Comment by elvismdev** [comment]
@timnolte I agree, let me know about your results testing this same patch on Vilcek, if it resolves this issue there as in the F1 website we can definitely merge this change and release a new bug fix version.

**Comment by timnolte** [comment]
@elvismdev I've confirmed also on Vilcek that this does indeed fix the issue.

**Comment by elvismdev** [comment]
Fixed by https://github.com/forumone/wp-cfm/pull/125
