### ISSUE TITLE
Add ACF support

### ISSUE THREAD

**Issue by mgibbsF1** [forumone/wp-cfm#36]
cc @jmslbam 

Adding ACF support into WP-CFM core. Based on the awesome work at https://github.com/level-level/wp-cfm-acf

**Comment by Flowgram** [comment]
Any news with this? How did it go in the end? 

Looking forward to decent ACF support.

Thanks!

**Comment by jmslbam** [comment]
I don't know if you want this default in the WP-CFM plugin. I mean, it's an honor, but it's code one needs to support till the end. Just like WP-CLI, they let you extend your own functionality/code in your own plugin so the plugin itself can focus on it's core. We, for example, only use this in 1 project so it's not actively supported :dart: 

@Flowgram you could install https://github.com/level-level/wp-cfm-acf to have this option within your reach.

People who don't use ACF don't need the code. FacetWP works the same, you want SearchWP  support? > Install the add-on.

**Comment by jmslbam** [comment]
Sorry for replying so late @mgibbsF1  :)

**Comment by mgibbs189** [comment]
@jmslbam true, maybe it's better to keep it separate and make sure the level-level extension is documented somewhere :)

**Comment by Derimagia** [comment]
We should either merge this in to wp-cfm or ACF. If we want this to be anything like Features for Drupal, developers shouldn't have to go out of their way to have this type of support...

**Comment by jmslbam** [comment]
Hi Dave,

ACF already has an export / import functionality so it probably won't get
into ACF core. And as stated earlier, I (we?) don't advice to get this code
into the core of WP-CFM, because it would divert from it's core purpose.

The little overhead of installing a small extra plugin is not that much of
an effort. Especially if you have a base project, as we do at our company,
so you don't have to download all the plugins every new project.

Greetings Jaime

**Comment by Derimagia** [comment]
If the "Core" principal of WP-CFM is to be light and have separate plugins for third party functionality then it's failing at it.

1) Wouldn't have "Custom Field Suite" support
2) **Would not mention "Advanced Custom Fields support in the future."**

Also, making these type of packages a third-party plugin will diminish the plugins value. Take a look at at WP-CFM ACF - it hasn't been touched in a year and was only tested on one project. That's insane seeing how useful it could be. The reason is almost completely the fact that no one knows about it.

So if you really think that making the core-plugin small is beneficial then it needs to have a plugin system that makes sense. It should remove all non-core-wordpress functionality and put them in separate plugins. Then it should have a "Plugin List" somewhere (Even if it's on the WP-CFM WP Page!)

**Comment by jmslbam** [comment]
An add-on page on the WP-CFM website is be a great idea.
The Github repo is right here and can be edited via Jekyll:
https://github.com/forumone/wp-cfm/tree/gh-pages

*Custom Field Suite field groups*
Well, true to that, can't argue with that :) I haven't seen that one
because I never used CFS. It's up to Matt to choose to split it from core
again and into an add-on or leave it just right there. Or to the one who
pleases and wants to send the Pull Requests.

*Mentioning ACF*
We can ask Matt to remove it and replace it with, check out more add-ons
like support for ACF etc.
Wait, even that can be done via a PR
https://github.com/forumone/wp-cfm/blob/master/readme.txt

So I understand the confusion and as we all can see, it can be fixed.  I,
personally, hope you can help if you would like to spend some time on it.
As we all know,  the overall issue with Open Source is available time... so
only if you have any.

Sincerely Jaime



If the "Core" principal of WP-CFM is to be light and have separate plugins
for third party functionality then it's failing at it.

1) Wouldn't have "Custom Field Suite" support
2) *Would not mention "Advanced Custom Fields support in the future."*

Also, making these type of packages a third-party plugin will diminish the
plugins value. Take a look at at WP-CFM ACF - it hasn't been touched in a
year and was only tested on one project. That's insane seeing how useful it
could be. The reason is almost completely the fact that no one knows about
it.

So if you really think that making the core-plugin small is beneficial then
it needs to have a plugin system that makes sense. It should remove all
non-core-wordpress functionality and put them in separate plugins. Then it
should have a "Plugin List" somewhere (Even if it's on the WP-CFM WP Page!)

—
Reply to this email directly or view it on GitHub
<https://github.com/forumone/wp-cfm/issues/36#issuecomment-182594284>.

**Comment by Derimagia** [comment]
I'll add it to the list of many open-source projects I want to contribute to :).

Are you aware of any other plugins for WP-CFM?

**Comment by mgibbs189** [comment]
@jmslbam @Derimagia 

The issue **is not** that we shouldn't built *any* integrations into WP-CFM.

The issue is that each integration increases technical burden. At this point, there simply wouldn't be enough contributors to ensure that built-in integrations would be continually tested.

That's why, whenever possible, I'd prefer to rely on the plugin authors themselves to add and maintain their own integrations (just like with `wp-cli`).

ACF is its own special snowflake though.

**Pros:**
- It's incredibly popular
- Adding ACF integration could encourage other developers to start using WP-CFM, or even build integration into their own plugins

**Cons:**
- Technical burden (ACF has historically been a moving target, and currently there's both ACF4 and ACF5, which require different handling code)
- Lack of time (and/or funding) to ensure continued maintenance and testing
- It has its own Import / Export system

**Comment by arh1** [comment]
> That's why, whenever possible, I'd prefer to rely on the plugin authors themselves to add and maintain their own integrations (just like with wp-cli).

Yeah, that seems key to me. Maybe there are special snowflakes (I'd recommend we think pretty hard about these), but -- like Features for Drupal -- as a general design principle it seems pretty crucial that we encourage other plugins to integrate w/ wp-cfm as opposed to the other way around.
