### ISSUE TITLE
Add ability to specify config import directory

### ISSUE THREAD

**Issue by arh1** [forumone/wp-cfm#40]
Similar to #38 , which is concerned with specifying the export directory for config push, we should add the ability to specify the import directory for config pull.

**Comment by mortona42** [comment]
A few things to work out:

Pulling a bundle with a specified source should keep track of where the bundle is located so diffs can continue to work.

**Comment by mortona42** [comment]
Should new bundles created in the interface have a source?  No source could just mean we use the default dir.  Sites already using this plugin won't have a source stored in the db.

**Comment by arh1** [comment]
Intended behavior:

* wp config pull foo --source=bar  # In the source directory 'bar', create a bundle in the db from bundle file 'foo.json' and give it a 'source' property with value 'bar', or update the 'foo' bundle in the db (already having 'source' property with value 'bar')
* wp config pull all --source=baz # In the source directory 'baz', create bundles in the db from any new bundle files and give them a 'source' property with value 'baz', and update any existing bundles in the db that have the 'source' property with value 'baz'

**Comment by mortona42** [comment]
Showing the source in the UI would be helpful to users I think.

**Comment by mortona42** [comment]
In order to store bundles in a plugin directory, get_file_bundles() needs to only look for .json files, and we may need to put a signature of some kind into the file (we can start with using .label).

**Comment by arh1** [comment]
This work should be considered along with "push --destination" in #51 .

The general workflow is assumed to be:
1. Site A: Create bundle in UI
2. Site A: Config push --destination via CLI *#See #51 . Only needed for first push, or when changing destination*
3. Site A: Commit and deploy
4. Site B: Config pull --source via CLI *#Must be the path where the bundle file exists, likely in the project repo at the same path as given for the destination above. Only needed for first pull, or when changing source*
5. Repeat steps 2-4

A few assumptions listed in #51 are worth reiterating here:

* A path is stored in the db with the bundle data
* The path is used for both the push destination and pull source unless a new path is specified explicitly as an argument on one of those commands, which will update the path in the db
* Paths are relative to the site root (not absolute, and not relative to the config directory)

**Comment by mortona42** [comment]
The source needs to be added to the UI for the save button to pass to the save function, otherwise source gets overridden.

**Comment by mortona42** [comment]
We need to check a given source to ensure that it's relative to the site root, or convert absolute paths.

**Comment by mortona42** [comment]
Some test cases for bugs spotted in development:

Path setting got overwritten for bundles that weren't being updated.  This happened in the UI when the save didn't include the bundle's path when updating settings.  It happened in code for wp-cli functions because path handling code was changed multiple times for different features.

Bundles in the default directory should not have a Path parameter in the db, as specified in a comment above.  Check that it's correctly populated, not empty, and not showing the default dir.

Check that diffs still work, both in wp-cli and via the interface.  Check that delete still works via the interface.  Check that bundles and show_bundle still works.  Note in bundles that it shows whether the bundle is in the db, filesystem, or both.  This command gives good output to check what wp-cfm bundle settings are in the db.

Error checking and output (valid path/bundle) could probably use more attention.  I'd like some feedback on provided output and expectations.
