### ISSUE TITLE
Add Git integration to WP-CLI integration

### ISSUE THREAD

**Issue by arh1** [forumone/wp-cfm#41]
We should add Git integration along with our WP-CLI integration, such that we can interact with a project's Git repo via options passed to config push from cli.  We'll be working on the following options (each of which we'll split out into their own issue):

* wp config push --add  # Runs “git add” after export.
* wp config push --branch=[name] # Create a new branch before committing
* wp config push --commit # Add and commit to git after exporting.
* wp config push --message # Commit message, used with --commit / --push
* wp config push --push # Also runs git push after committing.
* wp config push --remote # Select which remote to push to.

**Comment by jmslbam** [comment]
I don't know why you want extra code/functionality  like this just to mimic git and a git kind of flow.  Not that this is my repo or plugin to decide btw.  But these are all things that you already can do and should be all solved beyond/outside of the scope of this plugin.
For example,  WP-CLI doesn't have a bunch of combined commands because you could do it by piping bash output to another WP-CLI command.  
You also need to support all of that code and probably be adding why to much not related to config.  Besides that,  not everyone uses Git as their main version control.  But that last argument shouldn't be the main reason to decline a PR.  
Wrapping Git isn't the purpose of this plugin. Keep focus on it's core functionality. 
And if you still want it.  Wrap WP-CFM in a new command so you can split the code, because you can call WP-CLI command from your PHP and pass arguments to it. 
Just my 50cents. Ciao!

**Comment by mgibbs189** [comment]
@jmslbam has a good point. WP-CFM's purpose is to get settings in/out of WordPress. I don't think the transfer mechanism should be of any concern to the core plugin.

**Comment by arh1** [comment]
Thanks for the thoughts, and yeah, I see your point.  We at Forum One are doing some work around automating/consolidating various aspects of our development workflow, and while bundling this Git integration into WP-CFM was the simplest approach for us, I hear you that it's really a separate concern from the core of this plugin.  I'll be thinking about alternatives...

**Comment by arh1** [comment]
Closing per discussion above.

For posterity, we're taking a look at https://github.com/boonebgorges/wp-cli-git-helper for the transfer.
