### ISSUE TITLE
Support for multiple environments

### ISSUE THREAD

**Issue by ataylorme** [forumone/wp-cfm#95]
e.g. plugins enabled on staging vs. live

**Comment by ataylorme** [comment]
An action or filter system to activate the multiple environments feature and register environments.

Environments represented in the admin UI.

Bundle JSON organized on disk by each environment.

Ability to define the current environment with filters.

**Comment by ataylorme** [comment]
@elvismdev one thing to keep in mind is we would like support for Pantheon environments (`dev`, `test` and `live`) out of the box. These can be detected with [environment varaibles](https://pantheon.io/docs/read-environment-config).

If the environment is not one of those (e.g. a multidev) please assume `dev` (the default case).

The existing filters should be able to be used to override these assumptions.

**Comment by elvismdev** [comment]
@ataylorme PR #104 is ready for testing.

Detects and registers Pantheon environments out of the box when plugin is present in Pantheon hosting. 

New filter `wpcfm_multi_env` can be used to manually activate multiple environments feature and register them. Works in conjunction with `wpcfm_current_env`. This one also can be used to override the automatically detected Pantheon environments `dev`, `test`, `live`.

```
add_filter( 'wpcfm_multi_env', function() {
	return [
		'dev',
		'stage',
		'prod'
	];
} );
```

New filter `wpcfm_current_env` sets the current environment where the WordPress site is on. Is dependent of `wpcfm_multi_env` which must exists before and register the multiple environments where the WordPress site will be working on. Can be used to override the environment set automatically by `PANTHEON_ENVIRONMENT` constant when present in Pantheon hosting.

```
add_filter( 'wpcfm_current_env', function() {
	return 'dev';
} );
```

When multiple environments is active  and set, it is shown the name of this one at the WP-CFM admin page.

![Screen Shot 2019-07-15 at 12 10 09 AM](https://user-images.githubusercontent.com/3847077/61200092-29045b00-a695-11e9-9a38-1e2a92dbbfa1.png)

`JSON` or `YAML` bundle files are organized in a subfolder inside `wp-content/config`

<img width="290" alt="Screen Shot 2019-07-15 at 12 13 45 AM" src="https://user-images.githubusercontent.com/3847077/61200290-c8c1e900-a695-11e9-833b-c3df205b537d.png">

The filters `wpcfm_current_env` and `wpcfm_current_env` must be set in a [MU Plugin](https://wordpress.org/support/article/must-use-plugins/).

**Comment by ataylorme** [comment]
Thank you for the update @elvismdev. I have a lot of meetings today but will test it out later this week.

One thing I do want to make sure is that with this update we still allow users to solve the main problem of getting configuration changes made in one environment exported to code and deployed to another environment while also allowing for some per-environment settings.

I think active plugins is a good example. We should be able to accommodate both of the scenarios below:

1) Certain plugins are only active on the `dev` and `test` environments

2) A new plugin can be installed and configured in the `dev` environment and then that configuration bundled and deployed to other environments, e.g. `test` and `live`, so that the user does not have to do the configuration multiple times.

I'll leave it up to you to solve this in the UI but here are a few things I think could work:

1) A drop-down for which environment to export to when exporting a single bundle, defaulting to the current environment, could work.

2) A tabbed interface with the available environments, defaulting to the tab of the current environment, where bundles can be edited.

**Comment by ataylorme** [comment]
@elvismdev any update since my last comment?

**Comment by elvismdev** [comment]
Hi @ataylorme ! Sorry about the timing. I've swamped here during the last days, was planning to update you during today's meeting with more detail and live example. 

Answering your last comment. The work up in PR #104 does exactly the scenario you describe, but without the dropdown control on the backend UI and tabbed interface (yet), only by code.  

Once `wpcfm_multi_env` and `wpcfm_current_env` filters are added in a MU Plugin file like in the examples above, the multi-environment feature is recognized by the plugin. If in Pantheon host, all will be detected and enabled out of the box. No need to add them this time. 

However, adding the filters while in Pantheon gives the capacity to override or read the values that are detected (if that's helpful for some other custom action or edge case).

```php
// Plugin detected we are on Pantheon. 
 
add_filter( 'wpcfm_multi_env', function( $pantheon_envs ) {

    // $pantheon_envs contains an array with ['dev', 'test', 'live']
    // Read or update his values here if wanted. 
    
    return $pantheon_envs;
} );

add_filter( 'wpcfm_current_env', function( $pantheon_env ) {

        // $pantheon_env contains a string with `dev`, `test` or `live`.
        // Read or update this value here if wanted. 

	return $pantheon_env;
} );
```

Now, considering the scenario where I'm working on `dev` and I already have set a group of plugins active for this environment, among with other plugins configs, If I want to deploy this same configuration to the `test` environment, I can (one time only) change the return value of `wpcfm_current_env` filter to `test`. Then once I hit Push buttons from the current backend UI or fire the WP-CLI command `wp config push < bundle_name | all >` that will export the current config to code, but this time into the `wp-content/config/test/` folder. That makes you able to commit that new WP-CFM config file dedicated to the `test` environment and will apply those exported settings when deploying to `test`. Makes sense?

Since last Friday I've working on the UI side of things including the option that you mention above, where a user will able to do exactly this but from the plugin backend interface having a dropdown to select to which environment folder should be exported the current site config.

**Comment by ataylorme** [comment]
> Since last Friday I've working on the UI side of things including the option that you mention above, where a user will able to do exactly this but from the plugin backend interface having a dropdown to select to which environment folder should be exported the current site config.

Yes, I think this is the goal to have it be in UI instead of committing code multiple times (to override the environment to export and then again to reset it).

**Comment by elvismdev** [comment]
@ataylorme Backend UI experience is good to test now.

![multiple_env_demo](https://user-images.githubusercontent.com/3847077/62029800-6e964d00-b198-11e9-8eb4-b6167e6f6868.gif)

**Comment by elvismdev** [comment]
Feature now merged into `master`
